name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

permissions:
  contents: read
  id-token: 'write'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest


    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v2.0.0  
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}


          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.6.2
        cli_config_credentials_token: ${{ vars.TF_API_TOKEN }}
      
    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate -no-color


    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan -input=false


    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
